services:
  brig-mongo-dev:
    image: mongo:7.0
    container_name: brig-mongo-dev
    ports:
      - "28017:27017"
    volumes:
      - brig_mongo_data_dev:/data/db
    env_file:
      - .env.mongo.development

  brig-redis-dev:
    image: redis:7
    container_name: brig-redis-dev
    ports:
      - "7379:6379"
    volumes:
      - brig_redis_data_dev:/data
    env_file:
      - .env.redis.development
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

volumes:
  brig_mongo_data_dev:
    driver: local
  brig_redis_data_dev:
    driver: local
