services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    env_file:
      - .env.mongo

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    env_file:
      - .env.redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

volumes:
  mongo_data_dev:
    driver: local
  redis_data_dev:
    driver: local
