services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    env_file:
      - .env.mongo

volumes:
  mongo_data_dev:
    driver: local
